### ISSUE TITLE
Google Failed Answer

### ISSUE THREAD

**Issue by CChamper** [dyl10s/HQ-Trivia-Answers#1]
Every time the program runs after compiled, the answer is always failed. It successfully creates an Image but does not return any sort of answer.

**Comment by dyl10s** [comment]
Oh wow didn't think anyone would download this actually haha. You have to download some data to make this work I will upload it to see if I can make it work.

**Comment by dyl10s** [comment]
@CChamper go ahead and re pull it will be much bigger now but you should be able to just run the executable in the bin/debug folder.
