### ISSUE TITLE
How does this work???

### ISSUE THREAD

**Issue by Minaeskandar** [dyl10s/HQ-Trivia-Answers#2]

**Comment by Minaeskandar** [comment]
can it work on windows??

**Comment by Minaeskandar** [comment]
![capture](https://user-images.githubusercontent.com/16326577/38907222-cd282576-4288-11e8-9789-1d5f99e32c17.PNG)
this message keeps appearing when i chose run

**Comment by dyl10s** [comment]
Make sure the file is fully extracted and you have downloaded all dependencies from the repository. If you are still having issues I can help further.

**Comment by Minaeskandar** [comment]
Does the phone screen have to be in a certain position(x and y coordinates) on the pc screen so it can read the question???

**Comment by dyl10s** [comment]
You will see a little box pop up with a transparent background. You want to position it over just the question and the answers on your phone screen. I really should make an in depth tutorial on all the functions

**Comment by Minaeskandar** [comment]
That will be great if you made a video turtorial !!!

**Comment by dyl10s** [comment]
Maybe I will look into this later tonight, I just don't know if there is a demand for it. Also the project can only get an answer for about 50% of the questions due to the sheer complexity of them.

**Comment by dyl10s** [comment]
https://www.youtube.com/watch?v=C-07EpqFSgE&feature=youtu.be

**Comment by Minaeskandar** [comment]
Thank you so much!!!!

**Comment by Minaeskandar** [comment]
![a](https://user-images.githubusercontent.com/16326577/39074290-c2e61914-44be-11e8-9662-d8c0df302850.PNG)

**Comment by Minaeskandar** [comment]
this error keeps appearing???

**Comment by dyl10s** [comment]
Issues that could be happening
1) when you get eliminated and the answers are gray it has a really hard time reading
2) If it says fail then it didnt find an answer when it searched. this will happen for 25 - 50 percent of questions saddly
